# Generated by Django 5.2.12 on 2026-03-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role_id', 'permission_id', 'module_id')},
        ),
    ]
