# Generated by Django 5.2.12 on 2026-03-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_rolepermission_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermission',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='permission_id',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='role_id',
            new_name='role',
        ),
    ]
